-- 08-fees.sql
-- Fee rows now created automatically by trg_auto_fee (database/sql/08-triggers/02-trg-auto-fee.sql)
-- No manual inserts needed. This file is intentionally left empty — it stays
-- in run-all.sql's include order as a placeholder so that order doesn't shift,
-- but has nothing left to run.
--
-- The 30 fee rows this file used to insert (parcel_id 1000-1029, including the
-- specific paid_flag/paid_at values for DELIVERED parcels) are still present
-- in the database from before this trigger existed — trg_auto_fee only fires
-- on new INSERTs going forward, it does not retroactively touch existing rows.
