
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE customers ADD user_id NUMBER';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE customers ADD CONSTRAINT fk_customers_user
         FOREIGN KEY (user_id) REFERENCES users(id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -2264 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE customers ADD CONSTRAINT uq_customers_user
         UNIQUE (user_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE = -2264 THEN NULL; ELSE RAISE; END IF;
END;
/

PROMPT customers.user_id added (FK + UNIQUE to users.id).
